apps/dizimo/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # dizimistas
    url(r'^dizimistas/$', views.ListaDizimistas.as_view(), name='dizimistas'),
    url(r'^dizimistas/novo/$', views.NovoDizimista.as_view(), name='novo_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/edita/$', views.EditaDizimista.as_view(), name='edita_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/exibe/$', views.ExibeDizimista.as_view(), name='exibe_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/exibe/pdf$', views.ExibeDizimistaPDF.as_view(), name='exibe_dizimista_pdf'),
    url(r'^dizimistas/(?P<pk>\d+)/exclui/$', views.ExcluiDizimista.as_view(), name='exclui_dizimista'),

    # ofertas
    url(r'^ofertas/$', views.ListaOfertas.as_view(), name='ofertas'),
    url(r'^ofertas/nova/$', views.NovaOferta.as_view(), name='nova_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/edita/$', views.EditaOferta.as_view(), name='edita_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/exibe/$', views.ExibeOferta.as_view(), name='exibe_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/exclui/$', views.ExcluiOferta.as_view(), name='exclui_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/recibo/$', views.ReciboOferta.as_view(), name='recibo_oferta'),

    # dizimos
    url(r'^dizimos/$', views.ListaDizimos.as_view(), name='dizimos'),
    url(r'^dizimos/novo/$', views.NovoDizimo.as_view(), name='novo_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/edita/$', views.EditaDizimo.as_view(), name='edita_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/exibe/$', views.ExibeDizimo.as_view(), name='exibe_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/exclui/$', views.ExcluiDizimo.as_view(), name='exclui_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/recibo/$', views.ReciboDizimo.as_view(), name='recibo_dizimo'),
    url(r'^dizimos/(?P<ref>\d+)/clona/$', views.ClonaDizimo.as_view(), name='clona_dizimo'),

    # batismos
    url(r'^batismos/$', views.ListaBatismos.as_view(), name='batismos'),
    url(r'^batismos/novo/$', views.NovoBatismo.as_view(), name='novo_batismo'),
    url(r'^batismos/(?P<pk>\d+)/edita/$', views.EditaBatismo.as_view(), name='edita_batismo'),
    url(r'^batismos/(?P<pk>\d+)/exibe/$', views.ExibeBatismo.as_view(), name='exibe_batismo'),
    url(r'^batismos/(?P<pk>\d+)/exclui/$', views.ExcluiBatismo.as_view(), name='exclui_batismo'),
    url(r'^batismos/(?P<pk>\d+)/recibo/$', views.ReciboBatismo.as_view(), name='recibo_batismo'),

    # doacoes
    url(r'^doacoes/$', views.ListaDoacoes.as_view(), name='doacoes'),
    url(r'^doacoes/nova/$', views.NovaDoacao.as_view(), name='nova_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/edita/$', views.EditaDoacao.as_view(), name='edita_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/exibe/$', views.ExibeDoacao.as_view(), name='exibe_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/exclui/$', views.ExcluiDoacao.as_view(), name='exclui_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/recibo/$', views.ReciboDoacao.as_view(), name='recibo_doacao'),

    # paroquias
    url(r'^paroquias/$', views.ListaParoquias.as_view(), name='paroquias'),
    url(r'^paroquias/nova/$', views.NovaParoquia.as_view(), name='nova_paroquia'),
    url(r'^paroquias/(?P<pk>\d+)/edita/$', views.EditaParoquia.as_view(), name='edita_paroquia'),
    url(r'^paroquias/(?P<pk>\d+)/exclui/$', views.ExcluiParoquia.as_view(), name='exclui_paroquia'),

    # tipos de pagamentos
    url(r'^tipos_pagamentos/$', views.ListaTiposPagamentos.as_view(), name='tipos_pagamentos'),
    url(r'^tipos_pagamentos/novo/$', views.NovoTipoPagamento.as_view(), name='novo_tipo_pagamento'),
    url(r'^tipos_pagamentos/(?P<pk>\d+)/edita/$', views.EditaTipoPagamento.as_view(), name='edita_tipo_pagamento'),
    url(r'^tipos_pagamentos/(?P<pk>\d+)/exclui/$', views.ExcluiTipoPagamento.as_view(), name='exclui_tipo_pagamento'),

    # pagamentos
    url(r'^pagamentos/$', views.ListaPagamentos.as_view(), name='pagamentos'),
    url(r'^pagamentos/novo/$', views.NovoPagamento.as_view(), name='novo_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/exibe/$', views.ExibePagamento.as_view(), name='exibe_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/edita/$', views.EditaPagamento.as_view(), name='edita_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/exclui/$', views.ExcluiPagamento.as_view(), name='exclui_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/recibo/$', views.ReciboPagamento.as_view(), name='recibo_pagamento'),

    # relatorios
    url(r'^dizimistas/relatorios/aniversariantes/$', views.aniversariantes, name='aniversariantes'),
    url(r'^dizimistas/relatorios/aniversariantes/pdf$', views.RelatorioAniversariantesPDF.as_view(), name='relatorio_aniversariantes_pdf'),
    url(r'^dizimistas/relatorios/dizimistas/$', views.relatorio_dizimistas, name='relatorio_dizimistas'),
    url(r'^dizimistas/relatorios/dizimistas/pdf$', views.RelatorioDizimistasPDF.as_view(), name='relatorio_dizimistas_pdf'),
    url(r'^dizimistas/relatorios/ficha_dizimista/pdf$', views.FichaCadastralDizimistaPDF.as_view(), name='ficha_cadastral_dizimista_pdf'),
    url(r'^dizimistas/relatorios/ficha_batismo/pdf$', views.FichaCadastralBatismoPDF.as_view(), name='ficha_cadastral_batismo_pdf'),
    url(r'^dizimistas/relatorios/(?P<pk>\d+)/individual/pdf$', views.RelatorioIndividualDizimistaPDF.as_view(), name='relatorio_individual_dizimista_pdf'),

    url(r'^relatorios/pagamentos/$', views.relatorio_pagamentos, name='relatorio_pagamentos'),
    url(r'^relatorios/pagamentos/pdf$', views.RelatorioPagamentosPDF.as_view(), name='relatorio_pagamentos_pdf'),
    url(r'^relatorios/recimentos/geral/$', views.relatorio_geral_recebimentos, name='relatorio_geral_recebimentos'),
    url(r'^relatorios/recimentos/geral/pdf$', views.RelatorioGeralRecebimentosPDF.as_view(), name='relatorio_geral_recebimentos_pdf'),
    url(r'^relatorios/recimentos/batismos/$', views.relatorio_batismos, name='relatorio_batismos'),
    url(r'^relatorios/recimentos/batismos/pdf$', views.RelatorioBatismosPDF.as_view(), name='relatorio_batismos_pdf'),
    url(r'^relatorios/recimentos/dizimos/$', views.relatorio_dizimos, name='relatorio_dizimos'),
    url(r'^relatorios/recimentos/dizimos/pdf$', views.RelatorioDizimosPDF.as_view(), name='relatorio_dizimos_pdf'),
    url(r'^relatorios/recimentos/doacoes/$', views.relatorio_doacoes, name='relatorio_doacoes'),
    url(r'^relatorios/recimentos/doacoes/pdf$', views.RelatorioDoacoesPDF.as_view(), name='relatorio_doacoes_pdf'),
    url(r'^relatorios/recimentos/ofertas/$', views.relatorio_ofertas, name='relatorio_ofertas'),
    url(r'^relatorios/recimentos/ofertas/pdf$', views.RelatorioOfertasPDF.as_view(), name='relatorio_ofertas_pdf'),
]

sdizimo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from apps.comum import views


urlpatterns = [
    url(r'^', include('apps.dizimo.urls', namespace='dizimo')),  # dizimo app
    url(r'^autenticacao/', include('apps.autenticacao.urls')),  # autenticacao app
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/dizimo/models.py
from django.contrib.auth.models import User
from django.db import models
from localflavor.br.models import BRStateField
from sorl.thumbnail import ImageField


class Paroquia(models.Model):
    nome = models.CharField(max_length=250, blank=False, null=False, unique=True)
    endereco = models.CharField(max_length=250, blank=False, null=False, verbose_name='endereço')
    telefone = models.CharField(max_length=15, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    estado = BRStateField(blank=True, null=True)

    class Meta:
        ordering = ('nome', )
        permissions = (
            ("view_paroquia", "Can view paroquia"),
            ("list_paroquia", "Can list paroquia"),
        )

    def __str__(self):
        return self.nome


class Dizimista(models.Model):
    SEXO = [
        ['M', u'Masculino'],
        ['F', u'Feminino'],
    ]

    ESTADO_CIVIL = [
        ['C', 'Casado(a)'],
        ['S', 'Solteiro(a)'],
        ['D', 'Divorciado(a)'],
        ['V', 'Viúvo(a)'],
    ]

    nome = models.CharField(max_length=250, blank=False, null=False)
    endereco = models.CharField(max_length=250, blank=True, null=True, verbose_name='endereço')
    bairro = models.CharField(max_length=100, blank=True, null=True)
    cidade = models.CharField(max_length=100, blank=True, null=True)
    estado = BRStateField(blank=True, null=True)
    paroquia = models.ForeignKey(Paroquia, blank=False, null=False, verbose_name='paróquia')
    comunidade = models.CharField(max_length=100, blank=True, null=True)
    sexo = models.CharField(max_length=1, choices=SEXO, blank=False, null=False)
    estado_civil = models.CharField(max_length=1, choices=ESTADO_CIVIL, blank=True, null=True)
    data_nascimento = models.DateField(null=False, blank=False, verbose_name='data de nascimento')
    foto = ImageField(upload_to='dizimistas/fotos', null=True, blank=True)

    class Meta:
        ordering = ('nome', )
        permissions = (
            ("view_dizimista", "Can view dizimista"),
            ("list_dizimista", "Can list dizimista"),
        )

    def __str__(self):
        return self.nome


class Telefone(models.Model):
    TIPO = [
        ['CEL', u'Celular'],
        ['COM', u'Comercial'],
        ['RES', u'Residencial'],
    ]

    OPERADORA = [
        ['CLARO', u'Claro'],
        ['NET', u'Net'],
        ['OI', u'Oi'],
        ['TIM', u'Tim'],
        ['TVN', u'TVN'],
        ['VIVO', u'Vivo'],
    ]

    numero = models.CharField(max_length=15, blank=False, null=False, verbose_name='número')
    tipo = models.CharField(max_length=3, choices=TIPO, blank=False, null=False)
    operadora = models.CharField(max_length=5, choices=OPERADORA)
    dizimista = models.ForeignKey(Dizimista, related_name='telefones')

    def __str__(self):
        return '{0} ({1})'.format(self.numero, self.get_tipo_display())


class Recebimento(models.Model):
    cadastrado_em = models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')
    usuario = models.ForeignKey(User, verbose_name='usuário')
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    paroquia = models.ForeignKey(Paroquia, blank=False, null=False, verbose_name='paróquia')

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.paroquia = self.usuario.perfil.paroquia
        super(Recebimento, self).save(*args, **kwargs)


class Oferta(Recebimento):
    data = models.DateField(verbose_name='data')

    class Meta:
        ordering = ('-data', )
        permissions = (
            ("view_oferta", "Can view oferta"),
            ("list_oferta", "Can list oferta"),
        )

    def __str__(self):
        return 'R$ {0} - data {1}'.format(self.valor, self.data)


class Dizimo(Recebimento):
    data = models.DateField(verbose_name='data')
    dizimista = models.ForeignKey(Dizimista, related_name='dizimos')
    referencia = models.DateField(verbose_name='referência', help_text='Mês/Ano')

    class Meta:
        ordering = ('-referencia', '-data')
        unique_together = ('dizimista', 'referencia')
        permissions = (
            ("view_dizimo", "Can view dizimo"),
            ("list_dizimo", "Can list dizimo"),
        )

    def __str__(self):
        return '{0}: R$ {1} - {2}'.format(self.dizimista, self.valor, self.referencia.strftime('%m/%Y'))


class Batismo(Recebimento):
    nome_batizando = models.CharField(max_length=250, verbose_name='nome do batizando')
    nome_solicitante = models.CharField(max_length=250, verbose_name='nome do solicitante')
    data_batismo = models.DateField(verbose_name='data do batismo')
    hora_batismo = models.TimeField(verbose_name='hora do batismo')

    class Meta:
        ordering = ('-data_batismo', '-hora_batismo')
        permissions = (
            ("view_batismo", "Can view batismo"),
            ("list_batismo", "Can list batismo"),
        )

    def __str__(self):
        return '{0} batizado em {1}'.format(self.nome_batizando, self.data_batismo.strftime('%d/%m/%Y'))


class Doacao(Recebimento):
    descricao = models.CharField(max_length=250, verbose_name='descrição')
    data = models.DateField(verbose_name='data')

    class Meta:
        ordering = ('-data', )
        permissions = (
            ("view_doacao", "Can view doacao"),
            ("list_doacao", "Can list doacao"),
        )

    def __str__(self):
        return 'R$ {0} - data {1}'.format(self.valor, self.data)


class TipoPagamento(models.Model):
    descricao = models.CharField(max_length=250, verbose_name='descrição')
    paroquia = models.ForeignKey(Paroquia, blank=False, null=False, verbose_name='paróquia')

    class Meta:
        ordering = ('descricao', )
        permissions = (
            ("view_tipopagamento", "Can view tipopagamento"),
            ("list_tipopagamento", "Can list tipopagamento"),
        )

    def __str__(self):
        return self.descricao


class Pagamento(models.Model):
    tipo = models.ForeignKey(TipoPagamento, related_name='pagamentos')
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data = models.DateField(verbose_name='data')
    descricao = models.CharField(max_length=250, verbose_name='descrição')
    cadastrado_em = models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')
    usuario = models.ForeignKey(User, verbose_name='usuário')
    paroquia = models.ForeignKey(Paroquia, blank=False, null=False, verbose_name='paróquia')

    class Meta:
        ordering = ('-data', )
        permissions = (
            ("view_pagamento", "Can view pagamento"),
            ("list_pagamento", "Can list pagamento"),
        )

    def __str__(self):
        return '{1} - R$ {0}'.format(self.valor, self.tipo)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.paroquia = self.usuario.perfil.paroquia
        super(Pagamento, self).save(*args, **kwargs)

apps/dizimo/templates/relatorios/exibe_dizimista_pdf.html
{% extends 'base_pdf.html' %}

{% load static thumbnail %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div id="foto" class="foto_dizimista mb-4">
        {% if dizimista.foto %}
          {% thumbnail dizimista.foto "150x200" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="Foto de {{ user.username }}" class="img-thumbnail">
          {% endthumbnail %}
        {% else %}
          <img src="{% static 'img/no-user-foto.png' %}" width="150" height="200" alt="Foto 3x4" class="img-thumbnail">
        {% endif %}
      </div>
      <div class="col-9">
        <table class="table tabela_dados">
          <tr>
            <td width="130"><strong>Nº Cad.</strong></td>
            <td>{{dizimista.pk|stringformat:"03d"}}</td>
          </tr>
          <tr>
            <td><strong>Nome</strong></td>
            <td>{{dizimista.nome}}</td>
          </tr>
          <tr>
            <td><strong>Endereço</strong></td>
            <td>{{dizimista.endereco}}</td>
          </tr>
          <tr>
            <td><strong>Bairro</strong></td>
            <td>{{dizimista.bairro}}</td>
          </tr>
          <tr>
            <td><strong>Cidade</strong></td>
            <td>{{dizimista.cidade}}/{{dizimista.estado}}</td>
          </tr>
          <tr>
            <td><strong>Data de nascimento</strong></td>
            <td class="align-middle">{{dizimista.data_nascimento}}</td>
          </tr>
          <tr>
            <td><strong>Paróquia</strong></td>
            <td>{{dizimista.paroquia}}</td>
          </tr>
          <tr>
            <td><strong>Comunidade</strong></td>
            <td>{{dizimista.comunidade}}</td>
          </tr>
          <tr>
            <td><strong>Sexo</strong></td>
            <td>{{dizimista.get_sexo_display}}</td>
          </tr>
          <tr>
            <td><strong>Estado Civil</strong></td>
            <td>{{dizimista.get_estado_civil_display}}</td>
          </tr>
        </table>
      </div>

      <h3 class="telefones_dizimista">Telefones</h3>
      <table class="table">
        <thead class="thead">
          <tr class="titulo_tabela">
              <th scope="col">Número</th>
              <th scope="col">Tipo</th>
              <th scope="col">Operadora</th>
          </tr>
        </thead>
        <tbody>
          {% for telefone in dizimista.telefones.all %}
            <tr>
              <td {% if forloop.first %}class='primeira_linha'{% endif %}>{{telefone.numero}}</td>
              <td {% if forloop.first %}class='primeira_linha'{% endif %}>{{telefone.get_tipo_display}}</td>
              <td {% if forloop.first %}class='primeira_linha'{% endif %}>{{telefone.get_operadora_display}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

apps/dizimo/templates/relatorios/ficha_cadastral_batismo_pdf.html
{% extends 'base_pdf.html' %}

{% load static %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div id="foto" class="foto_dizimista mb-4">
        <img src="{% static 'img/no-user-foto.png' %}" width="150" height="200" alt="Foto 3x4" class="img-thumbnail">
      </div>
      <div class="col-9">
        <table class="table tabela_dados">
          <tr>
            <td width="150"><strong>Nome do batizando</strong></td>
            <td class="linha_dados">&nbsp;</td>
          </tr>
          <tr>
            <td><strong>Nome do solicitante</strong></td>
            <td class="linha_dados">&nbsp;</td>
          </tr>
          <tr>
            <td><strong>Data do batismo</strong></td>
            <td class="linha_dados">&nbsp;</td>
          </tr>
          <tr>
            <td><strong>Hora do batismo</strong></td>
            <td class="linha_dados">&nbsp;</td>
          </tr>
          <tr>
            <td><strong>Valor</strong></td>
            <td class="linha_dados">&nbsp;</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

apps/dizimo/templates/relatorios/relatorio_recebimentos.html
{% extends 'base.html' %}

{% block title %}{{ titulo }}{% endblock %}

{% block pageheader %}{{ titulo }}{% endblock %}

{% block breadcrumb %}
  <nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'inicio' %}">Início</a></li>
      <li class="breadcrumb-item active">{{ titulo }}</li>
    </ol>
  </nav>
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-header d-flex align-items-center">
      <h3 class="h4">Filtros para pesquisa</h3>
    </div>
    <div class="card-body">
      <form method="POST" novalidate>
        {% csrf_token %}
        {% include 'includes/filter_form.html' %}
      </form>
    </div>
  </div>

  {% if batismos or dizimos or doacoes or ofertas %}
    <div class="mb-4 d-flex flex-row-reverse">
      <a href="{% url url_relatorio %}?data_ini={{form.data_inicio.value}}&data_fim={{form.data_fim.value}}" target="_blank" class="btn btn-primary"><i class="fa fa-print" aria-hidden="true"></i> Imprimir</a>
    </div>
  {% endif %}

  {% if batismos %}
    <div class="card">
      <div class="card-header d-flex align-items-center">
        <h3 class="h4">Listagem de Batismos</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-inverse">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Batizando</th>
              <th scope="col">Solicitante</th>
              <th scope="col">Data do batismo</th>
              <th scope="col">Valor (R$)</th>
              <th scope="col">Registrado em</th>
              <th scope="col">Usuário responsável</th>
            </tr>
          </thead>
          <tbody>
            {% for batismo in batismos %}
              <tr>
                <td scope="row" width="60">
                  <a href="{% url 'dizimo:exibe_batismo' batismo.pk %}" title="Exibir"><i class="fa fa-search" aria-hidden="true"></i></a>
                  <a href="{% url 'dizimo:edita_batismo' batismo.pk %}" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                </td>
                <td>{{ batismo.nome_batizando }}</td>
                <td>{{ batismo.nome_solicitante }}</td>
                <td>{{ batismo.data_batismo|date:"d/m/Y" }} {{ batismo.hora_batismo }}</td>
                <td>{{ batismo.valor }}</td>
                <td>{{ batismo.cadastrado_em|date:"d/m/Y H:i" }}</td>
                <td>{{ batismo.usuario }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  {% if dizimos %}
    <div class="card">
      <div class="card-header d-flex align-items-center">
        <h3 class="h4">Listagem de Dízimos</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-inverse">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Dizimista</th>
              <th scope="col">Referência</th>
              <th scope="col">Valor (R$)</th>
              <th scope="col">Data</th>
              <th scope="col">Registrado em</th>
              <th scope="col">Usuário responsável</th>
            </tr>
          </thead>
          <tbody>
            {% for dizimo in dizimos %}
              <tr>
                <td scope="row" width="60">
                  <a href="{% url 'dizimo:exibe_dizimo' dizimo.pk %}" title="Exibir"><i class="fa fa-search" aria-hidden="true"></i></a>
                  <a href="{% url 'dizimo:edita_dizimo' dizimo.pk %}" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                </td>
                <td>{{ dizimo.dizimista }}</td>
                <td>{{ dizimo.referencia|date:"m/Y" }}</td>
                <td>{{ dizimo.valor }}</td>
                <td>{{ dizimo.data|date:"d/m/Y" }}</td>
                <td>{{ dizimo.cadastrado_em|date:"d/m/Y H:i" }}</td>
                <td>{{ dizimo.usuario }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  {% if doacoes %}
    <div class="card">
      <div class="card-header d-flex align-items-center">
        <h3 class="h4">Listagem de Doações</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-inverse">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Descrição</th>
              <th scope="col">Valor (R$)</th>
              <th scope="col">Data</th>
              <th scope="col">Registrado em</th>
              <th scope="col">Usuário responsável</th>
            </tr>
          </thead>
          <tbody>
            {% for doacao in doacoes %}
              <tr>
                <td scope="row" width="60">
                  <a href="{% url 'dizimo:exibe_doacao' doacao.pk %}" title="Exibir"><i class="fa fa-search" aria-hidden="true"></i></a>
                  <a href="{% url 'dizimo:edita_doacao' doacao.pk %}" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                </td>
                <td>{{ doacao.descricao }}</td>
                <td>{{ doacao.valor }}</td>
                <td>{{ doacao.data|date:"d/m/Y" }}</td>
                <td>{{ doacao.cadastrado_em|date:"d/m/Y H:i" }}</td>
                <td>{{ doacao.usuario }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  {% if ofertas %}
    <div class="card">
      <div class="card-header d-flex align-items-center">
        <h3 class="h4">Listagem de Ofertas</h3>
      </div>
      <div class="card-body">
        <table class="table table-hover">
          <thead class="thead-inverse">
            <tr>
              <th scope="col">#</th>
              <th scope="col">Valor (R$)</th>
              <th scope="col">Data</th>
              <th scope="col">Registrado em</th>
              <th scope="col">Usuário responsável</th>
            </tr>
          </thead>
          <tbody>
            {% for oferta in ofertas %}
              <tr>
                <td scope="row" width="60">
                  <a href="{% url 'dizimo:exibe_oferta' oferta.pk %}" title="Exibir"><i class="fa fa-search" aria-hidden="true"></i></a>
                  <a href="{% url 'dizimo:edita_oferta' oferta.pk %}" title="Editar"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                </td>
                <td>{{ oferta.valor }}</td>
                <td>{{ oferta.data|date:"d/m/Y" }}</td>
                <td>{{ oferta.cadastrado_em|date:"d/m/Y H:i" }}</td>
                <td>{{ oferta.usuario }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}

  <script>
    $(document).ready(function(){
      $('#id_data_inicio').mask("00/00/0000", {placeholder: "__/__/____"});
      $('#id_data_fim').mask("00/00/0000", {placeholder: "__/__/____"});
    });
  </script>
{% endblock %}