apps/dizimo/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    # dizimistas
    url(r'^dizimistas/$', views.ListaDizimistas.as_view(), name='dizimistas'),
    url(r'^dizimistas/novo/$', views.NovoDizimista.as_view(), name='novo_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/edita/$', views.EditaDizimista.as_view(), name='edita_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/exibe/$', views.ExibeDizimista.as_view(), name='exibe_dizimista'),
    url(r'^dizimistas/(?P<pk>\d+)/exibe/pdf$', views.ExibeDizimistaPDF.as_view(), name='exibe_dizimista_pdf'),
    url(r'^dizimistas/(?P<pk>\d+)/exclui/$', views.ExcluiDizimista.as_view(), name='exclui_dizimista'),

    # ofertas
    url(r'^ofertas/$', views.ListaOfertas.as_view(), name='ofertas'),
    url(r'^ofertas/nova/$', views.NovaOferta.as_view(), name='nova_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/edita/$', views.EditaOferta.as_view(), name='edita_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/exibe/$', views.ExibeOferta.as_view(), name='exibe_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/exclui/$', views.ExcluiOferta.as_view(), name='exclui_oferta'),
    url(r'^ofertas/(?P<pk>\d+)/recibo/$', views.ReciboOferta.as_view(), name='recibo_oferta'),

    # dizimos
    url(r'^dizimos/$', views.ListaDizimos.as_view(), name='dizimos'),
    url(r'^dizimos/novo/$', views.NovoDizimo.as_view(), name='novo_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/edita/$', views.EditaDizimo.as_view(), name='edita_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/exibe/$', views.ExibeDizimo.as_view(), name='exibe_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/exclui/$', views.ExcluiDizimo.as_view(), name='exclui_dizimo'),
    url(r'^dizimos/(?P<pk>\d+)/recibo/$', views.ReciboDizimo.as_view(), name='recibo_dizimo'),
    url(r'^dizimos/(?P<ref>\d+)/clona/$', views.ClonaDizimo.as_view(), name='clona_dizimo'),

    # batismos
    url(r'^batismos/$', views.ListaBatismos.as_view(), name='batismos'),
    url(r'^batismos/novo/$', views.NovoBatismo.as_view(), name='novo_batismo'),
    url(r'^batismos/(?P<pk>\d+)/edita/$', views.EditaBatismo.as_view(), name='edita_batismo'),
    url(r'^batismos/(?P<pk>\d+)/exibe/$', views.ExibeBatismo.as_view(), name='exibe_batismo'),
    url(r'^batismos/(?P<pk>\d+)/exclui/$', views.ExcluiBatismo.as_view(), name='exclui_batismo'),
    url(r'^batismos/(?P<pk>\d+)/recibo/$', views.ReciboBatismo.as_view(), name='recibo_batismo'),

    # doacoes
    url(r'^doacoes/$', views.ListaDoacoes.as_view(), name='doacoes'),
    url(r'^doacoes/nova/$', views.NovaDoacao.as_view(), name='nova_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/edita/$', views.EditaDoacao.as_view(), name='edita_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/exibe/$', views.ExibeDoacao.as_view(), name='exibe_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/exclui/$', views.ExcluiDoacao.as_view(), name='exclui_doacao'),
    url(r'^doacoes/(?P<pk>\d+)/recibo/$', views.ReciboDoacao.as_view(), name='recibo_doacao'),

    # paroquias
    url(r'^paroquias/$', views.ListaParoquias.as_view(), name='paroquias'),
    url(r'^paroquias/nova/$', views.NovaParoquia.as_view(), name='nova_paroquia'),
    url(r'^paroquias/(?P<pk>\d+)/edita/$', views.EditaParoquia.as_view(), name='edita_paroquia'),
    url(r'^paroquias/(?P<pk>\d+)/exclui/$', views.ExcluiParoquia.as_view(), name='exclui_paroquia'),

    # tipos de pagamentos
    url(r'^tipos_pagamentos/$', views.ListaTiposPagamentos.as_view(), name='tipos_pagamentos'),
    url(r'^tipos_pagamentos/novo/$', views.NovoTipoPagamento.as_view(), name='novo_tipo_pagamento'),
    url(r'^tipos_pagamentos/(?P<pk>\d+)/edita/$', views.EditaTipoPagamento.as_view(), name='edita_tipo_pagamento'),
    url(r'^tipos_pagamentos/(?P<pk>\d+)/exclui/$', views.ExcluiTipoPagamento.as_view(), name='exclui_tipo_pagamento'),

    # pagamentos
    url(r'^pagamentos/$', views.ListaPagamentos.as_view(), name='pagamentos'),
    url(r'^pagamentos/novo/$', views.NovoPagamento.as_view(), name='novo_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/exibe/$', views.ExibePagamento.as_view(), name='exibe_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/edita/$', views.EditaPagamento.as_view(), name='edita_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/exclui/$', views.ExcluiPagamento.as_view(), name='exclui_pagamento'),
    url(r'^pagamentos/(?P<pk>\d+)/recibo/$', views.ReciboPagamento.as_view(), name='recibo_pagamento'),

    # relatorios
    url(r'^dizimistas/relatorios/aniversariantes/$', views.aniversariantes, name='aniversariantes'),
    url(r'^dizimistas/relatorios/aniversariantes/pdf$', views.RelatorioAniversariantesPDF.as_view(), name='relatorio_aniversariantes_pdf'),
    url(r'^dizimistas/relatorios/dizimistas/$', views.relatorio_dizimistas, name='relatorio_dizimistas'),
    url(r'^dizimistas/relatorios/dizimistas/pdf$', views.RelatorioDizimistasPDF.as_view(), name='relatorio_dizimistas_pdf'),
    url(r'^dizimistas/relatorios/ficha_dizimista/pdf$', views.FichaCadastralDizimistaPDF.as_view(), name='ficha_cadastral_dizimista_pdf'),
    url(r'^dizimistas/relatorios/ficha_batismo/pdf$', views.FichaCadastralBatismoPDF.as_view(), name='ficha_cadastral_batismo_pdf'),
    url(r'^dizimistas/relatorios/(?P<pk>\d+)/individual/pdf$', views.RelatorioIndividualDizimistaPDF.as_view(), name='relatorio_individual_dizimista_pdf'),

    url(r'^relatorios/pagamentos/$', views.relatorio_pagamentos, name='relatorio_pagamentos'),
    url(r'^relatorios/pagamentos/pdf$', views.RelatorioPagamentosPDF.as_view(), name='relatorio_pagamentos_pdf'),
    url(r'^relatorios/recimentos/geral/$', views.relatorio_geral_recebimentos, name='relatorio_geral_recebimentos'),
    url(r'^relatorios/recimentos/geral/pdf$', views.RelatorioGeralRecebimentosPDF.as_view(), name='relatorio_geral_recebimentos_pdf'),
    url(r'^relatorios/recimentos/batismos/$', views.relatorio_batismos, name='relatorio_batismos'),
    url(r'^relatorios/recimentos/batismos/pdf$', views.RelatorioBatismosPDF.as_view(), name='relatorio_batismos_pdf'),
    url(r'^relatorios/recimentos/dizimos/$', views.relatorio_dizimos, name='relatorio_dizimos'),
    url(r'^relatorios/recimentos/dizimos/pdf$', views.RelatorioDizimosPDF.as_view(), name='relatorio_dizimos_pdf'),
    url(r'^relatorios/recimentos/doacoes/$', views.relatorio_doacoes, name='relatorio_doacoes'),
    url(r'^relatorios/recimentos/doacoes/pdf$', views.RelatorioDoacoesPDF.as_view(), name='relatorio_doacoes_pdf'),
    url(r'^relatorios/recimentos/ofertas/$', views.relatorio_ofertas, name='relatorio_ofertas'),
    url(r'^relatorios/recimentos/ofertas/pdf$', views.RelatorioOfertasPDF.as_view(), name='relatorio_ofertas_pdf'),
]

sdizimo/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from apps.comum import views


urlpatterns = [
    url(r'^', include('apps.dizimo.urls', namespace='dizimo')),  # dizimo app
    url(r'^autenticacao/', include('apps.autenticacao.urls')),  # autenticacao app
    url(r'^select2/', include('django_select2.urls')),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/autenticacao/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django_cleanup.signals import cleanup_pre_delete
from sorl.thumbnail import ImageField

from apps.dizimo.models import Paroquia


class Perfil(models.Model):
    ADMINISTRADOR = 1
    OPERADOR = 2
    SUPERVISOR = 3
    PAPEL_CHOICES = [
        (ADMINISTRADOR, 'Administrador'),
        (OPERADOR, 'Operador'),
        (SUPERVISOR, 'Supervisor'),
    ]
    PAPEL_CHOICES_EMPTY = [('', '---------')] + PAPEL_CHOICES

    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    papel = models.PositiveSmallIntegerField(choices=PAPEL_CHOICES, default=ADMINISTRADOR)
    foto = ImageField(upload_to='usuarios/fotos', null=True, blank=True)
    paroquia = models.ForeignKey(Paroquia, on_delete=models.CASCADE)

    class Meta:
        permissions = (
            ("view_perfil", "Can view perfil"),
            ("list_perfil", "Can list perfil"),
        )

    def __str__(self):
        return self.usuario.username

    def save(self, *args, **kwargs):
        # remove todos os grupos do usuario
        self.usuario.groups.clear()
        # adiciona grupo do usuario conforme o papel
        if self.papel == self.ADMINISTRADOR:
            # adiciona administrador dizimos e administrador autenticacao
            admin_usuarios = Group.objects.get(name='Administrador Usuários')
            admin_dizimos = Group.objects.get(name='Administrador Dízimos')
            self.usuario.groups.add(admin_usuarios)
            self.usuario.groups.add(admin_dizimos)
            # add_user_group_permissions(admin_usuarios, self.usuario)
            # add_user_group_permissions(admin_dizimos, self.usuario)
        elif self.papel == self.SUPERVISOR:
            # adiciona supervisor
            supervisor = Group.objects.get(name='Supervisor Dízimos')
            self.usuario.groups.add(supervisor)
            # add_user_group_permissions(supervisor, self.usuario)
        elif self.papel == self.OPERADOR:
            # adiciona operador
            operador = Group.objects.get(name='Operador Dízimos')
            self.usuario.groups.add(operador)
            # add_user_group_permissions(operador, self.usuario)
        super(Perfil, self).save(*args, **kwargs)

    def eh_administrador(self):
        return self.papel == self.ADMINISTRADOR


def get_name(self):
    return self.get_full_name()


User.add_to_class("__str__", get_name)


def add_user_group_permissions(group, user):
    user.user_permissions.clear()
    for p in group.permissions.all():
        user.user_permissions.add(p)


def sorl_delete(**kwargs):
    from sorl.thumbnail import delete
    delete(kwargs['file'])


cleanup_pre_delete.connect(sorl_delete)

# @receiver(post_save, sender=User)
# def cria_perfil_usuario(sender, instance, created, **kwargs):
#     if created:
#         Perfil.objects.create(usuario=instance)


# @receiver(post_save, sender=User)
# def salva_perfil_usuario(sender, instance, **kwargs):
#     instance.perfil.save()


class GerenciamentoGrupo(models.Model):
    grupo_gerenciador = models.ForeignKey(Group, related_name='grupo_gerenciador_set', on_delete=models.CASCADE)
    grupos_gerenciados = models.ManyToManyField(Group, related_name='grupos_gerenciados_set')
    eh_local = models.BooleanField(u'É Local?', default=False)

    NOME_GRUPO_GERENCIADOR_FORMAT = u'{} Administrador'

    class Meta:
        verbose_name = u"Gerenciamento de Grupo"
        verbose_name_plural = u"Gerenciamento de Grupos"

    def __unicode__(self):
        return u"{}".format(self.grupo_gerenciador.name)

    @classmethod
    def user_can_manage(cls, user):
        return user.is_superuser or cls.objects.filter(grupo_gerenciador__in=user.groups.all()).exists()

templates/base.html
{% load static thumbnail compress %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>SDízimo - {% block title %}{{ title }}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,700">
    <!-- Font Icons CSS-->
    {% comment %} <link rel="stylesheet" href="https://file.myfontastic.com/da58YPMQ7U5HY8Rb6UxkNf/icons.css"> {% endcomment %}
    {% compress css %}
    <!-- CSS files-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.blue.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.standalone.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <!-- Extra CSS-->
    {% block stylesheet %}{% endblock %}
    {% endcompress %}
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  </head>
  <body>
    {% block body %}
      <div class="page home-page">
        <!-- Main Navbar-->
        <header class="header">
          <nav class="navbar navbar-expand-lg">
            <!-- Search Box-->
            <div class="search-box">
              <button class="dismiss"><i class="icon-close"></i></button>
              <form id="searchForm" action="#" role="search">
                <input type="search" placeholder="O que você está procurando..." class="form-control">
              </form>
            </div>
            <div class="container-fluid">
              <div class="navbar-holder d-flex align-items-center justify-content-between">
                <!-- Navbar Header-->
                <div class="navbar-header mr-auto">
                  <!-- Navbar Brand -->
                  <a href="{% url 'inicio' %}" class="navbar-brand">
                    <div class="brand-text brand-big d-none d-xl-block"><strong>SDízimo</strong></div>
                    <div class="brand-text brand-small"><strong>SD</strong></div>
                  </a>
                  <!-- Toggle Button-->
                  <a id="toggle-btn" href="#" class="menu-btn active"><span></span><span></span><span></span></a>
                </div>
                <!-- Navbar Menu -->
                <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                  <!-- Search-->
                  {% comment %} <li class="nav-item"><a id="search" href="#" class="nav-link p-2" data-toggle="tooltip" title="Pesquisar"><i class="fa fa-search" aria-hidden="true"></i></a></li> {% endcomment %}
                  <li class="nav-item"><a href="{% url 'perfil_usuario' %}" class="nav-link p-2" data-toggle="tooltip" title="Meu perfil"><i class="fa fa-user-circle" aria-hidden="true"></i></a></li>
                  <li class="nav-item"><a href="{% url 'password_change' %}" class="nav-link p-2" data-toggle="tooltip" title="Alterar senha"><i class="fa fa-unlock-alt" aria-hidden="true"></i></a></li>
                  <!-- Logout    -->
                  <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link logout">Sair<i class="fa fa-sign-out"></i></a></li>
                </ul>
              </div>
            </div>
          </nav>
        </header>
        <div class="page-content d-flex align-items-stretch">
          <!-- Side Navbar -->
          <nav class="side-navbar">
            <!-- Sidebar Header-->
            <div class="sidebar-header d-flex align-items-center">
              <div class="avatar">
                <a href="{% url 'perfil_usuario' %}">
                  {% if user.perfil.foto %}
                    {% thumbnail user.perfil.foto "200x200" crop="center" as im %}
                      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="Foto de {{ user.username }}" class="img-fluid rounded-circle">
                    {% endthumbnail %}
                  {% else %}
                    <img src="{% static 'img/no-user-foto.png' %}" alt="{{ user.username }}" class="img-fluid rounded-circle">
                  {% endif %}
                </a>
              </div>
              <div class="title">
                <h1 class="h5">{{ user.get_full_name }}</h1>
                <p>{{ user.perfil.get_papel_display }}</p>
              </div>
            </div>
            <!-- Sidebar Navidation Menus-->
            <ul class="list-unstyled">
              <li {% if menu == 'inicio' %}class="active"{% endif %}><a href="{% url 'inicio' %}"><i class="fa fa-home fa-fw" aria-hidden="true"></i>Início</a></li>
              <li><a href="#menu_cadastros" aria-expanded="{% if menu == 'cadastros' %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-database fa-fw"></i>Cadastros</a>
                <ul id="menu_cadastros" class="collapse list-unstyled {% if menu == 'cadastros' %}show{% endif %}">
                  {% if user.perfil.eh_administrador %}
                    <li {% if menu_dropdown == 'paroquias' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:paroquias' %}">Paróquias</a></li>
                  {% endif %}
                  <li {% if menu_dropdown == 'tipos_pagamentos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:tipos_pagamentos' %}">Tipos de Pagamentos</a></li>
                </ul>
              </li>
              <li {% if menu == 'dizimistas' %}class="active"{% endif %}><a href="{% url 'dizimo:dizimistas' %}"><i class="fa fa-address-card-o fa-fw" aria-hidden="true"></i>Dizimistas</a></li>
              <li {% if menu == 'pagamentos' %}class="active"{% endif %}><a href="{% url 'dizimo:pagamentos' %}"><i class="fa fa-credit-card fa-fw" aria-hidden="true"></i>Pagamentos</a></li>
              <li><a href="#menu_recebimentos" aria-expanded="{% if menu == 'recebimentos' %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-money fa-fw"></i>Recebimentos</a>
                <ul id="menu_recebimentos" class="collapse list-unstyled {% if menu == 'recebimentos' %}show{% endif %}">
                  <li {% if menu_dropdown == 'batismos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:batismos' %}">Batismos</a></li>
                  <li {% if menu_dropdown == 'dizimos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:dizimos' %}">Dízimos</a></li>
                  <li {% if menu_dropdown == 'doacoes' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:doacoes' %}">Doações</a></li>
                  <li {% if menu_dropdown == 'ofertas' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:ofertas' %}">Ofertas</a></li>
                </ul>
              </li>
              <li><a href="#menu_relatorios" aria-expanded="{% if menu == 'relatorios' %}true{% else %}false{% endif %}" data-toggle="collapse"> <i class="fa fa-file-pdf-o fa-fw"></i>Relatórios</a>
                <ul id="menu_relatorios" class="collapse list-unstyled {% if menu == 'relatorios' %}show{% endif %}">
                  <li {% if menu_dropdown == 'lista_aniversariantes' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:aniversariantes' %}">Aniversariantes</a></li>
                  <li {% if menu_dropdown == 'relatorio_dizimistas' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_dizimistas' %}">Dizimistas</a></li>
                  <li {% if menu_dropdown == 'relatorio_batismos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_batismos' %}">Batismos</a></li>
                  <li {% if menu_dropdown == 'relatorio_dizimos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_dizimos' %}">Dízimos</a></li>
                  <li {% if menu_dropdown == 'relatorio_doacoes' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_doacoes' %}">Doações</a></li>
                  <li {% if menu_dropdown == 'relatorio_ofertas' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_ofertas' %}">Ofertas</a></li>
                  <li {% if menu_dropdown == 'relatorio_pagamentos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_pagamentos' %}">Pagamentos</a></li>
                  <li {% if menu_dropdown == 'relatorio_geral_recebimentos' %}class="active-dropdown"{% endif %}><a href="{% url 'dizimo:relatorio_geral_recebimentos' %}">Relatório geral de recebimentos</a></li>
                </ul>
              </li>
              {% if user.perfil.eh_administrador %}
                  <li {% if menu == 'usuarios' %}class="active"{% endif %}><a href="{% url 'usuarios' %}"><i class="fa fa-users fa-fw" aria-hidden="true"></i>Usuários</a></li>
              {% endif %}
            </ul>
          </nav>
          <div class="content-inner">
            <!-- Page Header-->
            <header class="page-header">
              <div class="container-fluid">
                <h2 class="no-margin-bottom">{% block pageheader %}{{ title }}{% endblock %}</h2>
              </div>
            </header>
            <!-- Breadcrumb-->
            {% block breadcrumb %}
            {% endblock %}
            <!-- Content -->
            <section id="main-section">
              <div class="container-fluid">
                {% if messages %}
                  {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ message }}</p>
                    </div>
                  {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock %}
              </div>
            </section>
          </div>
        </div>
      </div>
    {% endblock body %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.pt-BR.min.js' %}"></script>
    <script src="{% static 'js/locales/bootstrap-datepicker.pt-BR.min.js' %}"></script>
    <script src="{% static 'js/charts-2.5.0.min.js' %}"></script>
    {% compress js %}
    <script src="{% static 'js/jquery.cookie.js' %}"></script>
    <script src="{% static 'js/front.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <!-- datepicker config -->
    <script>
      $.fn.datepicker.defaults.format = "dd/mm/yyyy";
      $.fn.datepicker.defaults.language = "pt-BR";
      $.fn.datepicker.defaults.autoclose = true;
      $.fn.datepicker.defaults.todayBtn = true;
      $.fn.datepicker.defaults.todayHighlight = true;
      $.fn.datepicker.defaults.zIndexOffset = 1111;
    </script>
    <!-- ativacao dos tooltips -->
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
    {% block javascript %}{% endblock %}
    {% endcompress %}
  </body>
</html>

templates/base_pdf.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>SDízimo {% if titulo_relatorio %} - {{ titulo_relatorio }}{% endif %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <style>
      @page {
        size: A4;

        @frame header_frame {           /* Static Frame */
          -pdf-frame-content: header;
          left: 40pt; width: 512pt; top: 40pt; height: 100pt;
        }
        @frame content_frame {          /* Content Frame */
          left: 40pt; width: 512pt; top: 140pt; height: 659pt;
        }
        @frame footer_frame_1 {           /* Another static Frame */
          -pdf-frame-content: footer_left;
          left: 40pt; width: 512pt; top: 795pt; height: 30pt;
        }
        @frame footer_frame_2 {     /* Another static Frame */
          -pdf-frame-content: footer_right;
          left: 402pt; width: 150pt; top: 795pt; height: 30pt;
        }
      }
    </style>
    {% block extra_style %}{% endblock %}

    {% include 'includes/pdf_style.html' %}
  </head>

  <body>
    <div id="header">
      <h1>
        <strong>SDízimo</strong><br>
        <small>Sistema para controle e gerenciamento de dízimos e ofertas</small>
      </h1>
      {% if titulo_relatorio %}
        <div class="titulo_relatorio">
            # {{ titulo_relatorio }}
        </div>
      {% endif %}
    </div>

    <div id="footer_left">
      <small>Emitido por {{ user.get_full_name }} em {% now 'SHORT_DATETIME_FORMAT' %}.</small>
    </div>

    <div id="footer_right">
        <small>Página <pdf:pagenumber> de <pdf:pagecount></small>
    </div>

    <div class="content">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>